letsencrypt_renew_sync.sh, build/dep scripts upgraded

diff --git a/bin/dephtml b/bin/dephtml
--- a/bin/dephtml
+++ b/bin/dephtml
@@ -11,7 +11,7 @@ fi
 # 基础变量
 # 获取 $_OPER_PATH $_HTML_RUN $_HTML_LST_FILE $_HTMLSERVERS_LST_FILE _HTML_DEPLOY_DELAY 变量
 source ${EZDPL_HOME}/conf/deploy.include
-_usage="Usage: <htmlName> <version_dir>"
+_usage="Usage: <htmlName> <version_dir> <Confirm? y|n>"
 
 #参数变量
 _htmlName=$1
@@ -26,7 +26,7 @@ if [[ $# -eq 0 ]]; then
 fi
 if [[ ! -d ${_htmlSharedRunningDir} ]] ; then
     echo "$_usage"
-    echo "${_htmlSharedRunningDir} does not exist!";ls -1 ${_HTML_RUN} 2>/dev/null;exit 1
+    echo "${_htmlSharedRunningDir} does not exist.";ls -1 ${_HTML_RUN} 2>/dev/null;exit 1
 fi  
 if [[ $# -lt 2 ]]; then
     echo "$_usage"
@@ -36,7 +36,12 @@ if [[ $# -lt 2 ]]; then
 fi
 if [[ ! -d ${_path_new} ]]; then
     echo "$_usage"
-    echo "${_path_new} does not exists!";exit 1
+    echo "${_path_new} does not exists.";exit 1
+fi
+if [[ $3 = "n" ]]; then
+    _confirm="n"
+else
+    _confirm="y"
 fi
 
 set -u
@@ -45,24 +50,27 @@ _log_file=${_OPER_PATH}/dephtml.log
 touch $_log_file
 echo -e "\n\n" >> $_log_file
 
-# 获取html信息 #htmlDeployName|htmlDevName|htmlPort|gitBranch|gitRepo
+# 获取html信息，如有同名htmlName则只取第一条，去掉所有空格和TAB
+#htmlName|htmlDevName|gitBranch|gitRepo|codeDir|builtPath
+#    1          2          3       4       5       6
 if [[ -f "$_HTML_LST_FILE" ]]; then
     ls $_HTML_LST_FILE
-    _html_info=`egrep "^${_htmlName}\|" $_HTML_LST_FILE |egrep -v '(^ *#|^$)'|head -1 `
-    _htmlDeployName=` echo $_html_info|awk -F'|' '{print $1}'`
-
-
+    _htmlInfo=`cat $_HTML_LST_FILE | egrep -v "(^ *#|^$)" |awk -F'|' '{if ( $1 == "'${_htmlName}'" ) print $0}' | head -1`
 else
     echo "`date +%F_%T` $_HTML_LST_FILE does not exist." | tee -a $_log_file ; exit 1
 fi
-if [[ -z $_html_info ]]; then
-    echo "`date +%F_%T` $_htmlName not defined ." | tee -a $_log_file ; exit 1
+if [[ -z $_htmlInfo ]]; then
+    echo "`date +%F_%T` $_htmlName not configured in $_HTML_LST_FILE ."| tee -a $_log_file ; exit 1
 fi
+_htmlInfo=` echo "$_htmlInfo" | sed 's/[ \t]//g'`
+_builtPath=`echo "$_htmlInfo" | awk -F'|' '{print $6}'`
 
-# 获取 htmlservers 信息 #htmlDeployName|serverIp|serverUser|serverPort
+# 获取htmlservers信息，去掉所有空格和TAB
+#htmlDeployName|serverName|serverIp|serverUser|serverPort|targetPath|htmlPort
+#	1	   2	     3		 4	  5		6	7
 if [[ -f "$_HTMLSERVERS_LST_FILE" ]]; then
     ls $_HTMLSERVERS_LST_FILE
-    _servers=`egrep "^${_htmlName}\|" $_HTMLSERVERS_LST_FILE |egrep -v '^ *#'`
+    _servers=`cat $_HTMLSERVERS_LST_FILE | egrep -v '(^ *#|^$)' | awk -F'|' '{if ( $1 == "'${_htmlName}'" ) print $0}' `
 else
     echo "`date +%F_%T` $_HTMLSERVERS_LST_FILE does not exist." | tee -a $_log_file ; exit 1
 fi
@@ -70,24 +78,41 @@ if [[ -z $_servers ]]; then
     echo "`date +%F_%T` no htmlserver defined for $_htmlName ." | tee -a $_log_file ; exit 1
 fi
 
-echo -e "`date +%F_%T` $_htmlName $_version_dir\n\nServers:\n${_servers}"  | tee -a $_log_file
+_servers=`echo "$_servers" | sed 's/[ \t]//g'`
+echo -e "`date +%F_%T` $_htmlName $_version_dir\nhtmlInfo:\n${_htmlInfo}\nServers:\n${_servers}"  | tee -a $_log_file
 echo 
-#read -p "Enter Y to continue, Enter to quit: " _Y
-#if [[ $_Y != "Y" ]]; then
-#    echo "Aborted!" | tee -a $_log_file
-#    exit 
-#fi
+
+if [[ $_confirm = "y" ]]; then
+    read -p "Enter Y to continue, Enter to quit: " _Y
+    if [[ $_Y != "Y" ]]; then
+        echo "Aborted." | tee -a $_log_file
+        exit
+    fi
+fi
+for ((i=1;i<=5;i++)); do sleep 1 ; echo -n . ; done ; echo
 
 IFS=$'\n'
 for x in $_servers; do
-    _htmlServerName=` echo $x|awk -F'|' '{print $2}'`
-    _htmlServerPort=` echo $x|awk -F'|' '{print $4}'`
-    _htmlServerUser=` echo $x|awk -F'|' '{print $3}'`
-    echo "htmlName:        $_htmlName"
-    echo "htmlServer:      $_htmlServerUser@${_htmlServerName}:${_htmlServerPort}"
+    _htmlServerName=`echo $x|awk -F'|' '{print $2}'`
+    _htmlServerIp=`  echo $x|awk -F'|' '{print $3}'`
+    _htmlServerUser=`echo $x|awk -F'|' '{print $4}'`
+    _htmlServerPort=`echo $x|awk -F'|' '{print $5}'`
+    _targetPath=`    echo $x|awk -F'|' '{print $6}'`
+    echo "htmlName:       $_htmlName"		| tee -a $_log_file
+    echo "htmlServerName: $_htmlServerName"	| tee -a $_log_file
+    echo "htmlServer:     ${_htmlServerUser}@${_htmlServerIp}:${_htmlServerPort}:${_targetPath}" | tee -a $_log_file
+    echo "htmlServerPort: $_htmlServerPort"	| tee -a $_log_file
+    echo "htmlTargetPath: $_targetPath"		| tee -a $_log_file
     echo 
-    ssh -p ${_htmlServerPort} ${_htmlServerUser}@${_htmlServerName} "cd /opt/html && rm ${_htmlName} -f && ln -sf ${_path_new} ${_htmlName}; ls -l --color=always /opt/html/${_htmlName}"
-    echo "${_htmlServerName} updated ${_htmlName} to ${_path_new} ! " | tee -a $_log_file ; echo
-    
+    if [[ -n $_targetPath ]];then
+	# 有_targetPath ， 删除目的_targetPath，复制新的文件为_targetPath
+	ssh -p${_htmlServerPort} ${_htmlServerUser}@${_htmlServerIp} "rm ${_targetPath} -rf"
+	scp -P${_htmlServerPort} -r ${_path_new}/${_builtPath} ${_htmlServerUser}@${_htmlServerIp}:${_targetPath}
+        echo "${_htmlServerName} updated ${_htmlName} to ${_htmlServerUser}@${_htmlServerIp}:${_targetPath} ." | tee -a $_log_file ; echo
+    else
+	# 没有_targetPath，删除目的_htmlName的软连接，链接到新的部署目录
+        ssh -p${_htmlServerPort} ${_htmlServerUser}@${_htmlServerIp} "cd /opt/html && rm ${_htmlName} -f && ln -sf ${_path_new} ${_htmlName}; ls -l --color=always /opt/html/${_htmlName}"
+        echo "${_htmlServerName} updated ${_htmlName} to ${_path_new} ." | tee -a $_log_file ; echo
+    fi
     for ((i=1;i<=${_HTML_DEPLOY_DELAY};i++)); do sleep 1 ; echo -n . ; done ; echo
 done
diff --git a/bin/depwar b/bin/depwar
--- a/bin/depwar
+++ b/bin/depwar
@@ -11,8 +11,9 @@ fi
 # 基础变量
 # 获取 $_OPER_PATH $_WARS_RUN $_WAR_LST_FILE $_WEBSERVERS_LST_FILE _WAR_DEPLOY_DELAY 变量
 source ${EZDPL_HOME}/conf/deploy.include 
-_usage="Usage: depwar <war_name> <d|u> <version_dir>"
+_usage="Usage: depwar <war_name> <d|u> <version_dir> <Confirm? y|n>\n d - use deployWebxml\n u - undeploy "
 
+# 依赖目录： ${_WARS_RUN}/${_warName} , ${_warSharedRunningDir} , 
 #参数变量
 _warName=$1
 _oper=$2
@@ -20,103 +21,165 @@ _version_dir=$3
 _warSharedRunningDir="${_WARS_RUN}/${_warName}"
 _path_new=${_warSharedRunningDir}/${_version_dir}
 if [[ $# -eq 0 ]] ; then
-    echo "$_usage"
+    echo -e "$_usage"
+    echo "WARS_RUN: ${_WARS_RUN}"
     ls -1 "${_WARS_RUN}"
     exit 1
 fi
 if [[ ! -d ${_warSharedRunningDir} ]]; then
-    echo "$_usage"
-    echo "${_warSharedRunningDir} does not exist!";ls -1 ${_WARS_RUN} 2>/dev/null;exit 1
+    echo -e "$_usage"
+    echo "${_warSharedRunningDir} does not exist.";ls -1 ${_WARS_RUN} 2>/dev/null;exit 1
 fi
-if [[ $_oper != d ]] && [[ $_oper != u ]]; then
-    echo "$_usage"
-    echo "Only d|u is valid";exit 1
+if [[ $_oper != d ]] && [[ $_oper != u ]] ; then
+    echo -e "$_usage"
+    echo "Only d|u is valid.";exit 1
 fi
 if [[ $# -lt 3 ]] ; then
-    echo "$_usage"
+    echo -e "$_usage"
     echo  "${_warSharedRunningDir}"
     ls -1 "${_warSharedRunningDir}" 2>/dev/null | grep -v versions
     exit 1
 fi
 if [[ ! -d ${_path_new} ]]; then
-    echo "$_usage"
-    echo "${_path_new} does not exists!";exit 1
+    echo -e "$_usage"
+    echo "${_path_new} does not exists.";exit 1
+fi
+if [[ $4 = "n" ]]; then
+    _confirm="n"
+else 
+    _confirm="y"
 fi
 
 set -u 
+
 # 发版日志
 _log_file=${_OPER_PATH}/depwar.log
 touch $_log_file
 echo -e "\n\n" >> $_log_file
 
-# 获取wars信息 #warDevName|warDeployName|needRestart|webName|webPort|git_repo
+# 获取wars信息，如有同名warName则只取第一条，去掉所有空格和TAB 
+#warName|warDeployName|webName|configFilesPath|gitBranch|gitRepo|codeDir|runTest
+#   1       2            3          4              5        6       7       8
 if [[ -f "$_WAR_LST_FILE" ]]; then
     ls $_WAR_LST_FILE
-    _war_info=`cat $_WAR_LST_FILE | egrep -v '(^ *#|^$)' | awk -F'|' '{if ( $1 == "'${_warName}'" ) print $0}' | head -1 `
-    _warDeployName=` echo $_war_info|awk -F'|' '{print $2}'`
-    _warNeedRestart=`echo $_war_info|awk -F'|' '{print $3}'`
-    _warWebName=`    echo $_war_info|awk -F'|' '{print $4}'`
+    _warInfo=`cat $_WAR_LST_FILE | egrep -v '(^ *#|^$)' | awk -F'|' '{if ( $1 == "'${_warName}'" ) print $0}' | head -1 `
 else
-    echo "`date +%F_%T` $_WAR_LST_FILE does not exist!" | tee -a $_log_file ; exit 1
+    echo "`date +%F_%T` $_WAR_LST_FILE does not exist." | tee -a $_log_file ; exit 1
 fi
-if [[ -z $_war_info ]]; then
-    echo "`date +%F_%T` $_warName not defined!" | tee -a $_log_file ; exit 1
+if [[ -z $_warInfo ]]; then
+    echo "`date +%F_%T` $_warName not configured in $_WAR_LST_FILE ." | tee -a $_log_file ; exit 1
 fi
+_warInfo=`      echo "$_warInfo" |sed 's/[ \t]//g'`
+_warDeployName=`echo "$_warInfo" |awk -F'|' '{print $2}'`
+_warWebName=`   echo "$_warInfo" |awk -F'|' '{print $3}'`
 
-# 获取 webservers 信息 #webName|serverIp|serverUser|serverPort
+# 获取webservers信息，去掉所有空格和TAB 
+#webName|serverName|ServerIp|serverUser|serverPort|targetPath|deployMode(war/xml)|needRestart|webPort
+#   1        2		3	   4	 	5	6	  7			8	9
 if [[ -f "$_WEBSERVERS_LST_FILE" ]]; then
     ls $_WEBSERVERS_LST_FILE
-    _servers=`cat $_WEBSERVERS_LST_FILE | egrep -v '(^ *#|^$)' | awk -F'|' '{if ( $1 == "'${_warWebName}'" ) print $0}'`
+    _servers=`cat $_WEBSERVERS_LST_FILE | egrep -v '(^ *#|^$)' | awk -F'|' '{if ( $1 == "'${_warWebName}'" ) print $0}' `
 else
-    echo "`date +%F_%T` $_WEBSERVERS_LST_FILE does not exist!" | tee -a $_log_file ; exit 1
+    echo "`date +%F_%T` $_WEBSERVERS_LST_FILE does not exist."   | tee -a $_log_file ; exit 1
 fi
 if [[ -z $_servers ]]; then
-    echo "`date +%F_%T` no webserver defined for ${_warName}!" | tee -a $_log_file ; exit 1
+    echo "`date +%F_%T` no webserver defined for $_warWebName ." | tee -a $_log_file ; exit 1
 fi
 
-echo -e "`date +%F_%T` $_warName $_oper $_version_dir\nWarInfo:\n${_war_info}\nServers:\n${_servers}"  | tee -a $_log_file
+_servers=`echo "$_servers" | sed 's/[ \t]//g'`
+echo -e "`date +%F_%T` $_warName $_oper $_version_dir\nWarInfo:\n${_warInfo}\nServers:\n${_servers}"  | tee -a $_log_file
 echo 
 
-read -p "Enter Y to continue, Enter to quit: " _Y
-if [[ $_Y != "Y" ]]; then
-    echo "Aborted!" | tee -a $_log_file
-    exit 
+if [[ $_confirm = "y" ]]; then
+    read -p "Enter Y to continue, Enter to quit: " _Y
+    if [[ $_Y != "Y" ]]; then
+    	echo "Aborted." | tee -a $_log_file
+    	exit 
+    fi
 fi
 for ((i=1;i<=5;i++)); do sleep 1 ; echo -n . ; done ; echo
 
 IFS=$'\n'
 case $_oper in 
     d)
-	# 连接远程服务器，运行/usr/local/bin/deployWebxml脚本，携带必要参数
 	for x in $_servers; do 
 	    _webServerName=` echo $x|awk -F'|' '{print $2}'`
-	    _webServerPort=` echo $x|awk -F'|' '{print $4}'`
-	    _webServerUser=` echo $x|awk -F'|' '{print $3}'`
-	    echo "warName:        $_warName"
-	    echo "warDeployName:  $_warDeployName"
-	    echo "warNeedRestart: $_warNeedRestart"
-	    echo "warWebName:     $_warWebName"
-	    echo "webServer:      ${_webServerUser}@${_webServerName}:${_webServerPort}"
+	    _webServerIp=`   echo $x|awk -F'|' '{print $3}'`
+	    _webServerUser=` echo $x|awk -F'|' '{print $4}'`
+	    _webServerPort=` echo $x|awk -F'|' '{print $5}'`
+	    _webTargetPath=` echo $x|awk -F'|' '{print $6}'`
+	    _webDeployMode=` echo $x|awk -F'|' '{print $7}'`
+	    _webNeedRestart=`echo $x|awk -F'|' '{print $8}'`
+	    _webPort=`       echo $x|awk -F'|' '{print $9}'`
+	    echo "warName:        $_warName"		 | tee -a $_log_file 
+	    echo "warDeployName:  $_warDeployName"	 | tee -a $_log_file 
+	    echo "warWebName:     $_warWebName"		 | tee -a $_log_file 
+	    echo "webTargetPath:  $_webTargetPath"	 | tee -a $_log_file 
+	    echo "webDeployMode:  $_webDeployMode"	 | tee -a $_log_file 
+	    echo "webNeedRestart: $_webNeedRestart"	 | tee -a $_log_file 
+            echo "webPort:        $_webPort"      	 | tee -a $_log_file 
+            echo "webServerName:  $_webServerName"     	 | tee -a $_log_file 
+	    echo "webServer:      ${_webServerUser}@${_webServerIp}:${_webServerPort}" | tee -a $_log_file
 	    echo 
-            ssh -p ${_webServerPort} ${_webServerUser}@${_webServerName} "/usr/local/bin/deployWebxml ${_warWebName} ${_warDeployName} d ${_path_new}/${_warDeployName}.war ${_warNeedRestart}"
-	    echo "${_webServerName} deployed ${_path_new}/${_warDeployName}.war !" | tee -a $_log_file ; echo
+	    case $_webDeployMode in
+		xml)
+		    # 连接远程服务器，运行/usr/local/bin/deployWebxml脚本，携带必要参数
+                    ssh -p ${_webServerPort} ${_webServerUser}@${_webServerIp} \
+		      "/usr/local/bin/deployWebxml ${_warWebName} ${_warDeployName} d ${_path_new}/${_warDeployName}.war ${_webNeedRestart}"
+		    ;;
+	        war)
+		    # 直接上传war包到远程服务器的 targetPath
+	    	    if [[ $_webNeedRestart = 'Y' ]]; then
+			ssh -p${_webServerPort} ${_webServerUser}@${_webServerIp} "/usr/local/bin/tmc $_warWebName down"
+	    	    fi
+		    echo;echo "Uploading war file..."
+	    	    scp -p -P${_webServerPort} ${_path_new}/${_warDeployName}.war ${_webServerUser}@${_webServerIp}:${_webTargetPath}/
+	    	    if [[ $_webNeedRestart = 'Y' ]]; then
+			ssh -p${_webServerPort} ${_webServerUser}@${_webServerIp} "/usr/local/bin/tmc $_warWebName up"
+	    	    fi
+		    ;;
+		*)
+		    echo "deployMode of $_warWebName is misconfigured, should be xml/war ." | tee -a $_log_file ; exit 1
+		    ;;
+	    esac 
+	    echo "`date +%F_%T` ${_webServerName} deployed ${_path_new}/${_warDeployName}.war ." | tee -a $_log_file ; echo
 	    for ((i=1;i<=${_WAR_DEPLOY_DELAY};i++)); do sleep 1 ; echo -n . ; done ; echo
 	done
 	;;
     u)
-	# 连接远程服务器，运行/usr/local/bin/deployWebxml脚本，携带必要参数
 	for x in $_servers; do 
-	    _webServerName=` echo $x|awk -F'|' '{print $2}'`
-	    _webServerPort=` echo $x|awk -F'|' '{print $4}'`
-	    _webServerUser=` echo $x|awk -F'|' '{print $3}'`
-	    echo "warName:        $_warName"
-	    echo "warDeployName:  $_warDeployName"
-	    echo "warNeedRestart: $_warNeedRestart"
-	    echo "warWebName:     $_warWebName"
-	    echo "webServer:      ${_webServerUser}@${_webServerName}:${_webServerPort}"
-	    echo 
-	    ssh -p ${_webServerPort} ${_webServerUser}@${_webServerName} "/usr/local/bin/deployWebxml ${_warWebName} ${_warDeployName} u yes "
-	    echo "${_webServerName} undeployed ${_warName} !" | tee -a $_log_file ; echo
+            _webServerName=` echo $x|awk -F'|' '{print $2}'`
+            _webServerIp=`   echo $x|awk -F'|' '{print $3}'`
+            _webServerUser=` echo $x|awk -F'|' '{print $4}'`
+            _webServerPort=` echo $x|awk -F'|' '{print $5}'`
+            _webTargetPath=` echo $x|awk -F'|' '{print $6}'`
+            _webDeployMode=` echo $x|awk -F'|' '{print $7}'`
+            _webNeedRestart=`echo $x|awk -F'|' '{print $8}'`
+            _webPort=`       echo $x|awk -F'|' '{print $9}'`
+            echo "warName:        $_warName"             | tee -a $_log_file
+            echo "warDeployName:  $_warDeployName"       | tee -a $_log_file
+            echo "warWebName:     $_warWebName"          | tee -a $_log_file
+            echo "webTargetPath:  $_webTargetPath"       | tee -a $_log_file
+            echo "webDeployMode:  $_webDeployMode"       | tee -a $_log_file
+            echo "webNeedRestart: $_webNeedRestart"      | tee -a $_log_file
+            echo "webPort:        $_webPort"             | tee -a $_log_file
+            echo "webServerName:  $_webServerName"       | tee -a $_log_file 
+            echo "webServer:      ${_webServerUser}@${_webServerIp}:${_webServerPort}" | tee -a $_log_file
+            echo 
+            case $_webDeployMode in
+                xml)
+		    # 连接远程服务器，运行/usr/local/bin/deployWebxml脚本，携带必要参数
+		    ssh -p ${_webServerPort} ${_webServerUser}@${_webServerIp} "/usr/local/bin/deployWebxml ${_warWebName} ${_warDeployName} u yes "
+		    ;;
+		war)
+		    # 连接远程服务器，移除 war 文件
+		    ssh -p ${_webServerPort} ${_webServerUser}@${_webServerIp} "/usr/bin/mv -f ${_webTargetPath}/${_warDeployName}.war /tmp/"
+		    ;;
+                *)
+		    echo "deployMode of $_warWebName is misconfigured, should be xml/war ." | tee -a $_log_file ; exit 1
+                    ;;
+            esac
+   	    echo "${_webServerName} undeployed ${_warName} ." | tee -a $_log_file ; echo
 	done
 	;;
     *)
@@ -125,37 +188,4 @@ case $_oper in
 esac
 
 exit
-
-# README
-# 部署脚本环境变量
-# ${EZDPL_HOME}/conf/deploy.include
-# _DEP_WORK_USER 	部署脚本运行用户
-# _OPER_PATH=/opt/wars	war包构建 _OPER_PATH/build 待部署的war包 _OPER_PATH/todepoy/xxx.war war包重新打包 _OPER_PATH/cook
-# _WARS_RUN=/data/webShare/read/webapps	war包运行目录
-# _HTML_RUN=/data/webShare/read/html	html部署目录
-#
-# ${EZDPL_HOME}/conf/_config 
-# war包的生产配置文件，构建时会将这些文件更新到代码中，应用如果新增配置文件项，必须及时修改本目录下的文件。
-#
-# war包部署信息
-# ${EZDPL_HOME}/conf/war.lst 
-# 开发名|部署名|是否重启tomcat|web名（/opt/webs/xxx）|web端口（仅标识用）|git分支|git代码库地址 
-# #warDevName|warDeployName|needRestart|webName|webPort|gitBranch|gitRepo
-# 
-# web部署服务器信息
-# ${EZDPL_HOME}/conf/webservers.lst 
-# web名|服务器IP|服务器用户名|服务器SSH端口
-# #webName|serverName|serverUser|serverPort
-# 
-# html部署信息
-# ${EZDPL_HOME}/conf/html.lst
-# html部署目录名|html开发名|html web服务器端口（仅标识用）|git分支|git代码库地址
-# #htmlDeployName|htmlDevName|htmlPort|gitBranch|gitRepo
-# 
-# html部署服务器信息
-# ${EZDPL_HOME}/conf/htmlservers.lst
-# html部署目录名|服务器IP|服务器用户名|服务器SSH端口
-# #htmlDeployName|serverIp|serverUser|serverPort
-# 
-
 
