scs bugfix(duplicate host in hosts.lst prohibited)

diff --git a/bin/scs b/bin/scs
--- a/bin/scs
+++ b/bin/scs
@@ -44,18 +44,25 @@ else
     _ip=$_host
     _port=22
 fi
-if echo "$_hosts_port" | grep $_host; then    
-    _ip=`  echo "$_hosts_port" | grep $_host | awk '{print $1}'`
-    _user=`echo "$_hosts_port" | grep $_host | awk '{print $3}'`
-    _port=`echo "$_hosts_port" | grep $_host | awk '{print $4}'` 
-fi
 if [[ -n $4 ]]; then
     _dest=$4
 else
     _dest="."
 fi
 
-echo "$_user@$_ip:$_port"
+_host_info=`echo "$_hosts_port" | grep -w $_host`
+_host_info_line_count=`echo "$_host_info"|wc -l`
+if [[ $_host_info_line_count = 1 ]]; then    
+    _ip=`  echo "$_host_info" | grep $_host | awk '{print $1}'`
+    _user=`echo "$_host_info" | grep $_host | awk '{print $3}'`
+    _port=`echo "$_host_info" | grep $_host | awk '{print $4}'` 
+    echo "$_user@$_ip:$_port"
+else
+    echo "host not found or not unique."
+    echo "$_host_info"
+    exit 1
+fi
+
 case $2 in 
     u)
         scp -P $_port -p  $3 ${_user}@${_ip}:${_dest}
