ezdpl removes 'scp -p'

diff --git a/ezdpl/ezdpl b/ezdpl/ezdpl
--- a/ezdpl/ezdpl
+++ b/ezdpl/ezdpl
@@ -1,5 +1,9 @@
 #!/bin/bash
 # https://github.com/Panblack/ezdpl
+# Last update: 2016-03-30 13:32 (NO scp -p)
+
+
+_hint="Usage: ./ezdpl.sh <Silent Mode Y|N> <ip address>:[port] <app/version> [reboot Y|N(N)] [username(root)]"
 
 if [ -n "$1" ]; then 
   _silent=$1
@@ -10,7 +14,7 @@ if [ -n "$1" ]; then
     fi
   fi
 else
-  echo "silent. Usage: ./ezdpl.sh <Silent Mode Y|N> <ip address>:[port] <app/version> [reboot Y|N(N)] [username(root)]"
+  echo "silent. $_hint"
   exit 1
 fi
 
@@ -22,14 +26,14 @@ if [ -n "$2" ]; then
     _port="22"
   fi
 else
-  echo "ipaddress:port. Usage: ./ezdpl.sh <Silent Mode Y|N> <ip address>:[port] <app/version> [reboot Y|N(N)] [username(root)]"
+  echo "ipaddress:port. $_hint"
   exit 1
 fi
 
 if [ -n "$3" ]; then
   _app_version=$3
 else
-  echo "app/version. Usage: ./ezdpl.sh <Silent Mode Y|N> <ip address>:[port] <app/version> [reboot Y|N(N)] [username(root)]"
+  echo "app/version. $_hint"
   exit 1
 fi
 
@@ -91,26 +95,39 @@ if [ ! -d "./$_app_version" ]; then
 fi
 
 # Everything seems OK. Go!
+echo >> log.txt
+echo -n "`date +%Y-%m-%d_%H:%M:%S` ./ezdpl Y $_ipaddress:$_port $_app_version $_reboot $_username" >> log.txt
+
 # Run pre.sh on the target server
 if [ -f "./$_app_version/pre.sh" ]; then
-  /usr/bin/scp -p -P$_port ./$_app_version/pre.sh $_username@$_ipaddress:/tmp/
+  /usr/bin/scp -q -P$_port ./$_app_version/pre.sh $_username@$_ipaddress:/tmp/
   ssh -p$_port $_username@$_ipaddress 'source /etc/profile; sh /tmp/pre.sh'
-  echo "$_username@$_ipaddress:/tmp/pre.sh executed: $?"
+  if [[ $? != 0 ]];then 
+    echo "$_username@$_ipaddress:/tmp/pre.sh Failed. EXIT!!"
+    exit 1
+  else
+    echo "$_username@$_ipaddress:/tmp/pre.sh executed: $?"
+  fi
 fi
 
 # Start copy app/version/files/*
 if [ -d ./$_app_version/files  ]; then 
   echo "Start to copy ./$_app_version/files/*"
   echo "......"
-  /usr/bin/scp -rpq -P$_port ./$_app_version/files/* $_username@$_ipaddress:/
+  /usr/bin/scp -rq -P$_port ./$_app_version/files/* $_username@$_ipaddress:/
   echo "./$_app_version/files/* copied: $?"
 fi
 
 # Run fin.sh on the target server
 if [ -f "./$_app_version/fin.sh" ]; then
-  /usr/bin/scp -p -P$_port ./$_app_version/fin.sh $_username@$_ipaddress:/tmp/
+  /usr/bin/scp -q -P$_port ./$_app_version/fin.sh $_username@$_ipaddress:/tmp/
   ssh -p$_port $_username@$_ipaddress 'source /etc/profile; sh /tmp/fin.sh'
-  echo "$_username@$_ipaddress:/tmp/fin.sh executed: $?"
+  if [[ $? != 0 ]];then
+    echo "$_username@$_ipaddress:/tmp/fin.sh Failed. EXIT!!"
+    exit 1
+  else
+    echo "$_username@$_ipaddress:/tmp/fin.sh executed: $?"
+  fi
 fi
 
 # Reboot target server.
@@ -122,6 +139,5 @@ if [ "$_reboot" = "Y" ]; then
 fi
 echo "Target Server: ${_ipaddress} done!"; echo
 
-echo "`date +%Y-%m-%d_%H:%M:%S`, $_ipaddress, $_app_version, $_reboot" >>log.txt
-
-# End of ezdpl.sh
+echo " OK " >> log.txt
+# End of ezdpl
