deployWebxml fixed

diff --git a/servers/websrv/javasrv/files/usr/local/bin/deployWebxml b/servers/websrv/javasrv/files/usr/local/bin/deployWebxml
--- a/servers/websrv/javasrv/files/usr/local/bin/deployWebxml
+++ b/servers/websrv/javasrv/files/usr/local/bin/deployWebxml
@@ -3,10 +3,9 @@
 # vars: _BASES_DIR _WAR_RUNNING_PATH
 source /usr/local/bin/japp.include
 funHelp() {
-    echo -e "Usage:  deployWebxml <web_name> <war_name> <d/u/r> <version_dir> "
-    echo -e "Sample: deployWebxml backendapi api2 d 20171201-124622 	#Deploy 'api2' of version 20171201-124622 to '${_BASES_DIR}/backendapi'"
+    echo -e "Usage:  deployWebxml <web_name> <war_deploy_name> <d|u> <full_war_path> [Y|N]"
+    echo -e "Sample: deployWebxml backendapi api2 d /path/to/api2.war N	#Deploy   /path/to/api2.war to '${_BASES_DIR}/backendapi'"
     echo -e "Sample: deployWebxml backendapi api2 u yes 		#Undeploy 'api2' from '${_BASES_DIR}/backendapi'"
-    echo -e "Sample: deployWebxml backendapi api2 r 20171125-180556	#Rollback 'api2' to version 20171125-180556"
     echo -e "Available webs:\n`ls -1 ${_BASES_DIR} ` " ; echo
 }
 
@@ -16,31 +15,44 @@ if [[ $# -lt 3 ]] ; then
 fi
 
 _web_name=$1
-_war_name=$2
+_war_deploy_name=$2
 _oper=$3
-_version_dir=$4
-if [[ -z $_version_dir ]];then
-    echo "version dir required, check these out:"
-    ls -lh --color=auto --time-style=long-iso ${_WAR_RUNNING_PATH}/${_war_name} ; exit 1
+_full_war_path=$4
+_restart=$5
+if [[ -z $_full_war_path ]];then
+    echo "Full path of war file required"; exit 1 
+fi
+
+
+if [[ -z $_restart ]]; then
+    _restart="N"
 fi
 set -u 
 
 _war_xml_path="${_BASES_DIR}/$_web_name/conf/Catalina/localhost/"
-_war_xml="${_war_xml_path}/${_war_name}.xml"
-_war_torun="${_WAR_RUNNING_PATH}/${_war_name}/${_version_dir}/${_war_name}.war"
+_war_xml="${_war_xml_path}/${_war_deploy_name}.xml"
 
 case $_oper in 
     d) 
       	# Deploy new/updated war file
         mkdir -p $_war_xml_path
 	# wait for nfs delay
-	while true ; do 
-	    test -f $_war_torun && echo "<Context docBase='$_war_torun' />" > $_war_xml && break
+	for ((i=1;i<10;i++));do
+	    echo -n "."
+	    sleep 1
+	    test -f $_full_war_path && echo "<Context docBase='$_full_war_path' />" > $_war_xml && break
 	done
-   	echo "$_war_torun Deployed!"
+	if [[ $i = 10 ]];then
+	    echo "$_full_war_path NOT FOUND! "; exit 1
+	fi
+	echo 
+   	echo "$_full_war_path Deployed!"
+	if [[ $_restart = "Y" ]];then
+	    /usr/local/bin/tmc $_web_name rs 
+	fi
 	;;
     u)
-	if [[ $_version_dir = yes ]]; then
+	if [[ $_full_war_path = yes ]]; then
       	    # UnDeploy war file
     	    if [[ -f $_war_xml ]]; then
             	mv -f $_war_xml /tmp/
@@ -50,17 +62,8 @@ case $_oper in
     	    fi
         fi
 	;;
-    r)
-	# Roll back
-    	if [[ -f $_war_xml ]]; then
-    	    echo "<Context docBase='$_war_torun' />" > $_war_xml
-    	    echo "Rollback to $_war_torun !"
-    	else
-	    echo "$_war_xml does not exists."; funHelp;  exit 1
-    	fi
-	;;
     *)
-	echo "Only d/u/r is valid."
+	echo "Only d|u is valid."
 	;;
 esac
 
